# Generated by Django 5.2.5 on 2025-08-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_video', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='BrollClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('start', models.FloatField()),
                ('duration', models.FloatField()),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broll_clips', to='renderer.inputdata')),
            ],
        ),
        migrations.CreateModel(
            name='PiPClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('duration', models.FloatField()),
                ('overlay', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pip_clips', to='renderer.inputdata')),
            ],
        ),
    ]
