# Generated by Django 5.2.5 on 2025-08-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0002_inputdata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipclip',
            name='zoom_direction',
            field=models.CharField(blank=True, choices=[('', 'No zoom'), ('left', 'Left'), ('center', 'Center'), ('right', 'Right')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pipclip',
            name='zoom_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipclip',
            name='zoom_start',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
