# Generated by Django 5.1.5 on 2025-10-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0003_pipclip_zoom_direction_pipclip_zoom_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brollclip',
            name='file',
            field=models.FileField(max_length=500, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='main_video',
            field=models.FileField(max_length=500, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='pipclip',
            name='overlay',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/'),
        ),
    ]
