# Generated by Django 5.1.5 on 2025-10-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0004_alter_brollclip_file_alter_inputdata_main_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='completed_video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='outputs/'),
        ),
    ]
