# Generated by Django 5.1.5 on 2025-10-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the pre-production video', max_length=255)),
                ('pip_video', models.FileField(help_text='Pre-production PiP video file', upload_to='preproduction/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated')),
            ],
            options={
                'verbose_name': 'Pre-Production Video',
                'verbose_name_plural': 'Pre-Production Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
