# Generated by Django 5.1.5 on 2025-10-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproduction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preproduction',
            name='main_video',
            field=models.FileField(blank=True, help_text='Pre-production main video file', null=True, upload_to='preproduction/'),
        ),
    ]
