# Generated by Django 5.1.5 on 2025-10-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproduction', '0002_preproduction_main_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='preproduction',
            name='completed',
            field=models.BooleanField(default=False, help_text='Mark as completed'),
        ),
    ]
